# Map tmux config reload to PREFIX+R
unbind r
bind r source-file ~/.config/tmux/tmux.conf

# Turn on mouse support
set -g mouse on

# Set default terminal
set -g default-terminal "tmux-256color"

# Start windows and panes at 1, not 0
set -g base-index 1
setw -g pane-base-index 1

# Split panes using | and - in the current directory
bind | split-window -h -c "#{pane_current_path}"
bind - split-window -v -c "#{pane_current_path}"

# Set pane navigation to use vim directional keys
bind-key h select-pane -L
bind-key j select-pane -D
bind-key k select-pane -U
bind-key l select-pane -R


# Override default splits to use current directory
bind '"' split-window -c "#{pane_current_path}"
bind % split-window -h -c "#{pane_current_path}"

# Plugins (Installl with PREFIX+I)
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'catppuccin/tmux'

# Set status bar to the top of the window
 set-option -g status-position top

# Configure the catppuccin plugin
set -g @catppuccin_flavor "mocha"
set -g @catppuccin_window_status_style "rounded"
set -g @plugin 'tmux-plugins/tmux-cpu'


# Load catppuccin
# run ~/.config/tmux/plugins/catppuccin.tmux

# Make the status line pretty and add some modules
set -g status-right-length 100
set -g status-left-length 100
set -g status-left ""

set -g status-right "#{E:@catppuccin_status_application}"

set -agF status-right "#{E:@catppuccin_status_cpu}"

# Init TMUX plugin manager (keep this line at the very bottom of tmux.conf)

run '~/.config/tmux/plugins/tpm/tpm'
